import { useState, type FormEvent, type ReactNode, type CSSProperties } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { post } from '../../lib/api'

export const landingRoutes=[['/trang-chu','Trang chủ'],['/koc','Dành cho KOC'],['/doanh-nghiep','Doanh nghiệp'],['/marketplace','Khám phá KOC'],['/ai-clone','Video đại diện'],['/bang-gia','Bảng giá'],['/cong-dong','Cộng đồng'],['/ho-tro','Hỗ trợ']] as const
const logo='https://res.cloudinary.com/drxum5uxt/image/upload/v1785865656/LogoDaXoaNen_r82hx2.png'
const footerLogo='/images/koc-viet-logo.png'
export function Header(){const[o,setO]=useState(false);return <header className="lp-header"><div className="lp-header-inner"><Link to="/trang-chu" className="lp-logo" aria-label="KOC Việt"><img src={logo} alt="KOC Việt"/></Link><nav id="landing-navigation" className={`lp-nav ${o?'open':''}`}>{landingRoutes.map(([to,label])=><NavLink key={to} to={to} onClick={()=>setO(false)} className={({isActive})=>isActive?'active':''}>{label}</NavLink>)}<div className="lp-auth-btns"><Link to="/login" className="btn ghost sm">Đăng nhập</Link><Link to="/tuyen-koc" className="btn primary sm">Đăng ký</Link></div></nav><button className="lp-burger" type="button" aria-label={o?'Đóng trình đơn':'Mở trình đơn'} aria-controls="landing-navigation" aria-expanded={o} onClick={()=>setO(!o)}>☰</button></div></header>}
export function Footer(){return <footer className="lp-footer"><div className="lp-footer-inner"><div className="lp-footer-top"><div className="lp-footer-brand"><Link className="lp-footer-home-link" to="/trang-chu" aria-label="KOC Việt — về trang chủ"><img className="lp-footer-logo" src={footerLogo} alt="" width="52" height="52"/><span className="lp-footer-wordmark">KOC VIỆT</span></Link><p>KOC Việt — nền tảng booking KOC/KOLs thuộc NetViet.</p></div><div className="lp-footer-cols"><div className="lp-footer-col"><h4>Về chúng tôi</h4><Link to="/trang-chu">Về chúng tôi</Link><Link to="/bang-gia">Bảng giá & Hạng KOC</Link><Link to="/ai-clone">Dịch vụ AI Clone Avatar</Link><Link to="/cong-dong">Cộng đồng tỉnh thành</Link></div><div className="lp-footer-col"><h4>Hỗ trợ</h4><Link to="/ho-tro">Câu hỏi thường gặp</Link><Link to="/ho-tro">Điều khoản sử dụng</Link><Link to="/ho-tro">Chính sách bảo mật</Link></div><div className="lp-footer-col"><h4>Liên hệ</h4><a className="lp-footer-contact-link" href="tel:+84812986898">Hotline: 0812 98 68 98</a><a className="lp-footer-contact-link" href="tel:+84813487686">Hotline: 0813 487 686</a><a className="lp-footer-contact-link" href="mailto:kocviet@netviettv.com.vn">Email: kocviet@netviettv.com.vn</a><p className="lp-footer-hours">Giờ làm việc: 9:00–18:00 · Thứ 2–Thứ 7</p></div></div></div></div><div className="lp-footer-bottom-wrap"><div className="lp-footer-bottom"><p>© KOC Việt — NetViet. Bảo lưu mọi quyền.</p></div></div></footer>}
export function Shell({children,className=''}:{children:ReactNode;className?:string}){return <div className={`lp-body ${className}`.trim()}><Header/>{children}<Footer/></div>}
export function Media({src,alt,video=false,ratio='16/9',priority=false}:{src:string;alt:string;video?:boolean;ratio?:string;priority?:boolean}){return <figure className={`lp-media ${video?'lp-media-video':''}`} style={{'--ratio':ratio} as CSSProperties}><div className="lp-media-inner">{video?<video src={src} controls playsInline/>:<img src={src} alt={alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} width={priority?1450:undefined} height={priority?1085:undefined}/>}</div></figure>}
export function Hero({eyebrow,title,sub,image,primary=['Bắt đầu ngay','/explore'],secondary,variant}:{eyebrow:string;title:string;sub:string;image:string;primary?:[string,string];secondary?:[string,string];variant?:'home'}){return <section className={`lp-hero has-media ${variant==='home'?'lp-hero-home':''}`.trim()}><div className="lp-hero-inner"><span className="lp-eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lp-sub">{sub}</p><div className="lp-hero-cta"><Link className="btn grad nv-lift" to={primary[1]}>{primary[0]}</Link>{secondary&&<Link className="btn outline-white nv-lift" to={secondary[1]}>{secondary[0]}</Link>}</div></div><div className="lp-hero-media"><Media src={image} alt={title} ratio="4/3" priority={variant==='home'}/></div></section>}
export function Section({title,children,tint=false}:{title:string;children:ReactNode;tint?:boolean}){return <section className={`lp-section ${tint?'tint':''}`}><div className="lp-section-head"><h2>{title}</h2></div>{children}</section>}
export function Cards({items,columns=3}:{items:Array<[string,string,string?]>;columns?:2|3|4|5}){return <div className={`lp-grid-${columns}`}>{items.map(([title,body,icon])=><article className="lp-card lp-reveal" key={title}>{icon&&<div className="lp-benefit-icon">{icon}</div>}<h3>{title}</h3><p>{body}</p></article>)}</div>}
export function Steps({items}:{items:Array<[string,string]>}){return <div className="lp-steps">{items.map(([title,body],i)=><div className="lp-step" key={title}><div className="num">{i+1}</div><p><strong>{title}</strong><br/>{body}</p></div>)}</div>}
export function Faq({items}:{items:Array<[string,string]>}){const[o,setO]=useState<number|null>(null);return <div>{items.map(([q,a],i)=><div className={`lp-acc-item ${o===i?'open':''}`} key={q}><button className="lp-acc-q" onClick={()=>setO(o===i?null:i)}>{q}<span>{o===i?'−':'+'}</span></button><div className="lp-acc-a"><p>{a}</p></div></div>)}</div>}
export function Cta({title,primary=['Đăng ký miễn phí','/login'],secondary}:{title:string;primary?:[string,string];secondary?:[string,string]}){return <section className="lp-cta-final"><h2>{title}</h2><div className="lp-hero-cta"><Link className="btn navy" to={primary[1]}>{primary[0]}</Link>{secondary&&<Link className="btn ghost" to={secondary[1]}>{secondary[0]}</Link>}</div></section>}
export function LeadForm({source,title='Nhận tư vấn miễn phí'}:{source:string;title?:string}){const[f,setF]=useState({name:'',phone:'',company:'',need:''}),[done,setDone]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setError('');try{await post('/api/lead',{...f,source});setDone(true)}catch(x){setError(x instanceof Error?x.message:'Không gửi được')}}return <div className="lp-contact-wrap" id="contact-form"><div className="lp-card">{done?<div className="lp-contact-success" style={{display:'block'}}><div className="ico"><img src="/images/check-circle.svg" alt="" aria-hidden="true" style={{width:"1em",height:"1em",verticalAlign:"-0.125em"}} /></div><h3>Đã ghi nhận yêu cầu!</h3></div>:<><h3>{title}</h3><form className="lp-contact-form" onSubmit={submit}>{([['name','Họ tên'],['phone','Số điện thoại'],['company','Doanh nghiệp']] as const).map(([k,l])=><div className="field" key={k}><label>{l}</label><input required={k!=='company'} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}<div className="field"><label>Nội dung cần tư vấn</label><textarea rows={3} value={f.need} onChange={e=>setF({...f,need:e.target.value})}/></div>{error&&<div className="err">{error}</div>}<button className="btn primary">Gửi yêu cầu</button></form></>}</div></div>}
