import { Link } from 'react-router-dom'
import { Cards,Cta,Faq,Hero,LeadForm,Media,Section,Shell,Steps } from './LandingComponents'
const img={home:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785312022/BANNER_TRANG_CH%E1%BB%A6_rjdtn2.jpg',koc:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785312036/BANNER_TRANG_KOC_qjho2n.jpg',business:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785312034/booking_koc_d%E1%BB%85_d%C3%A0ng_nh%C6%B0_%C4%91%E1%BA%B7t_xe_jwapy0.jpg',market:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785313898/c%E1%BA%A3_m%E1%BB%99t_th%E1%BB%8B_tr%C6%B0%E1%BB%9Dng_koc_trong_b%E1%BB%99_l%E1%BB%8Dc_ynzysz.jpg',ai:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785313898/banner_ai_clone_av_i0rjqx.jpg',price:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785313899/b%E1%BA%A3ng_gi%C3%A1_u79tuy.jpg',community:'https://res.cloudinary.com/drxum5uxt/image/upload/v1785313892/kh%C3%A1ch_h%C3%A0ng_t%E1%BB%89nh_n%C3%A0o-koc_t%E1%BB%89nh_%C4%91%C3%B3_psuq1g.jpg'}
const flow:Array<[string,string]>=[
  ['TÌM & CHỌN','Doanh nghiệp lọc KOC theo ngành hàng, tỉnh, hạng, giá; xem hồ sơ với chỉ số hiệu quả thật và bảng giá công khai.'],
  ['BOOKING & ĐẶT CỌC','Gửi yêu cầu kèm link dữ liệu sản phẩm để KOC kiểm tra. Thanh toán tạm giữ vào ví đảm bảo của nền tảng.'],
  ['SẢN XUẤT & ĐĂNG BÀI','KOC xác nhận, tự sản xuất content đúng chất giọng của mình và đăng bài kèm link affiliate riêng.'],
  ['ĐO LƯỜNG & CHI TRẢ','Hệ thống ghi nhận click, đơn hàng theo thời gian thực. Hoàn thành: KOC nhận 95% phí booking + hoa hồng; doanh nghiệp nhận báo cáo minh bạch.'],
]

const activityItems=[
  ['Booking mới','Thương hiệu mỹ phẩm vừa gửi yêu cầu đến một Micro KOC','2 phút trước'],
  ['KOC mới tham gia','Một KOC ngành Ẩm thực tại TP. Hồ Chí Minh vừa hoàn tất hồ sơ','5 phút trước'],
  ['Chiến dịch hoàn thành','Booking ngành Mẹ & Bé vừa được nghiệm thu và giải ngân','9 phút trước'],
]

function ActivitySection(){return <section className="lp-activity-section" aria-label="Hoạt động KOC thời gian thực"><div className="lp-activity-container"><div className="lp-activity-header"><div className="lp-activity-title-wrap"><span className="lp-activity-pulse-dot" aria-hidden="true"/><span className="lp-activity-header-tag">TRỰC TIẾP 24/7</span><h3 className="lp-activity-heading">Hoạt động Booking &amp; KOC mới nhất</h3></div><span className="lp-activity-sub">Cập nhật liên tục từ hệ thống KOC Việt</span></div><div className="lp-activity-list" tabIndex={0}>{activityItems.map(([label,body,time],index)=><article className="lp-activity-row" data-activity-type={['booking_received','registered','booking_completed'][index]} key={body}><span className="lp-activity-badge">{label}</span><span className="lp-activity-text">{body}</span><time className="lp-activity-time">{time}</time></article>)}</div></div></section>}

export function HomeLanding(){return <Shell>
  <Hero eyebrow="NỀN TẢNG BOOKING KOC/KOLs MINH BẠCH" title="Booking KOC dễ như đặt xe. Giá công khai. Hiệu quả đo được." sub="KOC Việt kết nối trực tiếp doanh nghiệp với KOC/KOLs trên toàn quốc: mỗi KOC một trang hồ sơ với bảng giá cố định niêm yết theo ngành hàng — chọn đúng người, thấy đúng giá, chốt booking trong vài phút. Tiền giữ an toàn trong ví đảm bảo, chỉ giải ngân khi việc hoàn thành." image={img.home} primary={['Đăng ký làm KOC — miễn phí','/tuyen-koc']} secondary={['Tìm KOC cho chiến dịch của bạn','/explore']}/>
  <div className="lp-stat-strip"><div className="lp-stat"><strong>300.000</strong> — KOC/KOLs mục tiêu trên toàn quốc</div><div className="lp-stat"><strong>200.000</strong> — Doanh nghiệp đồng hành</div><div className="lp-stat"><strong>34</strong> — Tỉnh thành phủ cộng đồng KOC</div><div className="lp-stat"><strong>5%</strong> — Mức phí dịch vụ duy nhất, không phí ẩn</div></div>
  <ActivitySection/>
  <Section title="Bạn là ai trong hệ sinh thái KOC Việt?"><div className="lp-grid-2"><article className="lp-card lp-card-big"><h3>DÀNH CHO KOC/KOLs — Thu nhập của bạn, giá của bạn</h3><p>Tự niêm yết mức phí theo từng ngành hàng trong khung giá 4 hạng. Nhận booking từ doanh nghiệp cả nước, cộng thêm hoa hồng affiliate trên mỗi đơn hàng. Nhận 95% giá trị mỗi booking — đối soát tự động, rút tiền về tài khoản trong 24h.</p><Link to="/koc" className="btn primary">Trở thành KOC ngay</Link></article><article className="lp-card lp-card-big"><h3>DÀNH CHO DOANH NGHIỆP — Đúng người, đúng giá, đúng đơn hàng</h3><p>Duyệt hàng trăm nghìn hồ sơ KOC theo ngành hàng, tỉnh thành, mức giá và hiệu quả thật từ dữ liệu affiliate. Booking theo bảng giá niêm yết — không thương lượng lòng vòng, không báo giá mù mờ. Thanh toán qua ví đảm bảo, chỉ trả tiền cho kết quả được xác nhận.</p><Link to="/doanh-nghiep" className="btn primary">Nhận tư vấn miễn phí</Link></article></div></Section>
  <Section title="4 bước cho một chiến dịch trọn vẹn" tint><div className="lp-section-media lp-reveal lp-media-howitworks"><Media src="https://quankle2004.quankle2004.workers.dev/videos/how-it-works.mp4" alt="Video giới thiệu quy trình chiến dịch KOC Việt" video ratio="21/9"/></div><Steps items={flow}/></Section>
  <Section title="Điều mà thị trường booking KOC đang thiếu — chúng tôi làm trước tiên"><div className="lp-grid-4">{[['Giá niêm yết công khai','Lần đầu tiên tại Việt Nam, phí booking KOC minh bạch, phân theo 4 hạng Nano – Micro – Mid – Macro.'],['Ví đảm bảo (escrow)','Doanh nghiệp không sợ mất tiền, KOC không sợ bị quỵt phí. Tiền chỉ giải ngân khi hai bên xác nhận hoàn thành.'],['Hiệu quả bằng số thật','Chỉ số chuyển đổi của mỗi KOC tính từ dữ liệu affiliate thực tế, không tự khai báo, không mua follower ảo.'],['Đánh giá hai chiều','Doanh nghiệp chấm điểm KOC, KOC chấm điểm doanh nghiệp. Uy tín tích luỹ quyết định thứ hạng hiển thị.']].map(([title,body])=><article className="lp-card" key={title}><p><strong>{title}</strong> — {body}</p></article>)}</div></Section>
  <CategorySection/>
  <section className="lp-section"><div className="lp-banner"><h3>Mới: Dịch vụ AI Clone Avatar — thu nhập không cần quay video mỗi ngày</h3><p>Tham gia chương trình AI Clone Avatar: NetViet trực tiếp booking và sản xuất video cho bạn, bạn chỉ duyệt và đăng — vẫn nhận trọn phí booking cùng hoa hồng affiliate.</p><Link to="/ai-clone" className="btn grad">Tìm hiểu AI Clone Avatar →</Link></div></section>
  <section className="lp-section tint"><div className="lp-grid-2"><div className="lp-quote"><div className="stars">★★★★★</div><p>“Trước đây mình mất cả tuần đàm phán giá với từng nhãn. Giờ nhãn tự đến vì giá của mình treo sẵn trên hồ sơ — tháng cao điểm mình nhận 11 booking.” — Linh Chi, Micro KOC ngành Làm đẹp, Đà Nẵng</p></div><div className="lp-quote"><div className="stars">★★★★★</div><p>“Chi 30 triệu cho 8 KOC qua KOC Việt, chúng tôi biết chính xác từng đồng tạo ra bao nhiêu đơn. Điều đó chưa agency nào làm được cho chúng tôi.” — Giám đốc Marketing, thương hiệu mỹ phẩm nội địa</p></div></div></section>
  <Cta title="Booking minh bạch. Thanh toán an tâm. Kết nối bền vững." primary={['Đăng ký làm KOC — miễn phí','/tuyen-koc']} secondary={['Booking KOC ngay hôm nay','/explore']}/>
</Shell>}

const homeCategories=['Mỹ phẩm & Làm đẹp','Mẹ & Bé','Ẩm thực F&B','Thời trang','Điện tử gia dụng','Sức khoẻ','Du lịch địa phương','Tài chính cá nhân','Giáo dục','Thương mại điện tử']
function CategorySection(){return <Section title="Phủ mọi ngành hàng đang tăng trưởng" tint><div className="lp-section-media lp-reveal"><Media src="https://res.cloudinary.com/drxum5uxt/image/upload/v1785488594/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_3_n84ryp.jpg" alt="Minh hoạ các ngành hàng đang tăng trưởng" ratio="21/9"/></div><div className="lp-chip-row">{homeCategories.map(category=><span className="lp-chip" key={category}>{category}</span>)}</div></Section>}
export function KocLanding(){return <Shell><Hero eyebrow="DÀNH CHO KOC/KOLs" title="Bạn định giá. Nền tảng mang booking đến. Ví tự cộng tiền." sub="Mở gian hàng năng lực, niêm yết phí theo ngành hàng và nhận thêm hoa hồng affiliate." image={img.koc} primary={['Đăng ký làm KOC','/tuyen-koc']}/><Section title="Một bài đăng — hai dòng thu nhập"><Cards columns={2} items={[["95% phí booking","Nhận phần lớn giá trị booking khi hoàn thành."],["Hoa hồng affiliate","Tiếp tục nhận thu nhập từ đơn hàng."]]}/></Section><Section title="5 bước để bắt đầu — dưới 15 phút" tint><Steps items={[["TẠO TÀI KHOẢN","Xác thực email."],["KHAI BÁO KÊNH","Thêm mạng xã hội."],["NIÊM YẾT GIÁ","Chọn ngành và phí."],["KÝ HỢP ĐỒNG","Ký điện tử."],["NHẬN BOOKING","Bật trạng thái hợp tác."]]}/></Section><Section title="Càng làm tốt, khung giá càng mở"><Cards columns={4} items={[["Nano","Uy tín gần gũi."],["Micro","Tối ưu chuyển đổi."],["Mid","Độ phủ toàn quốc."],["Macro","Chiến dịch lớn."]]}/></Section><Section title="Câu hỏi thường gặp"><Faq items={[["Đăng ký có mất phí không?","Không thu phí đăng ký hoặc thành viên."],["Khi nào nhận tiền?","Sau khi booking hoàn thành và đối soát."],["Ai quyết định giá?","KOC niêm yết trong khung giá theo hạng."]]}/></Section><Cta title="Biến sức ảnh hưởng thành thu nhập minh bạch." primary={['Trở thành KOC','/tuyen-koc']}/></Shell>}
export function BusinessLanding(){return <Shell><Hero eyebrow="DÀNH CHO DOANH NGHIỆP & NHÃN HÀNG" title="Chọn người — Hợp giá — Chốt ngay." sub="Mọi KOC niêm yết giá công khai theo ngành hàng, kèm chỉ số hiệu quả thật." image={img.business} primary={['Tìm KOC ngay','/explore']} secondary={['Nhận tư vấn','/ho-tro']}/><Section title="Giải quyết bằng thiết kế, không bằng lời hứa"><Cards items={[["Tìm đúng người","Lọc theo ngành, tỉnh, hạng và hiệu suất.","🔎"],["Biết đúng giá","Giá công khai trước khi booking.","💵"],["Đo đúng kết quả","Báo cáo và đối soát cùng hệ thống.","📊"]]}/></Section><Section title="Hai luồng — tuỳ quy mô" tint><Cards columns={2} items={[["TỰ BOOKING QUA MARKETPLACE","Phù hợp SME và chiến dịch đơn lẻ."],["NETVIET ĐIỀU PHỐI","Phù hợp chiến dịch lớn, nhiều KOC."]]}/></Section><Section title="Booking trong 5 phút"><Steps items={flow}/></Section><LeadForm source="landing-business"/><Cta title="Mỗi đồng chi ra đều đo được kết quả." primary={['Khám phá Marketplace','/explore']}/></Shell>}
export function MarketplaceLanding(){return <Shell><Hero eyebrow="MARKETPLACE KOC/KOLs" title="Cả một thị trường KOC trong một bộ lọc." sub="Hồ sơ được xác minh — lọc theo ngành, tỉnh, hạng, giá và hiệu quả thật." image={img.market} primary={['Mở Marketplace','/explore']}/><Section title="Lọc thông minh cho từng chiến dịch"><Cards items={[["Theo ngành hàng","Làm đẹp, thời trang, ẩm thực, công nghệ."],["Theo địa phương","Đúng tiếng nói tại thị trường mục tiêu."],["Theo ngân sách","So sánh giá ngay trên hồ sơ."]]}/></Section><Section title="Mỗi hồ sơ là một bản chào hàng đầy đủ" tint><Media src="https://res.cloudinary.com/drxum5uxt/image/upload/v1785383806/h%E1%BB%93_s%C6%A1_koc_ihq9lf.jpg" alt="Hồ sơ KOC"/></Section><Cta title="Từ hồ sơ đến bài đăng — một đường thẳng." primary={['Tìm KOC ngay','/explore']}/></Shell>}
export function AiCloneLanding(){return <Shell><Hero eyebrow="DỊCH VỤ CỘNG THÊM DÀNH CHO KOC" title="Thu nhập vẫn chạy — kể cả ngày bạn không quay video." sub="NetViet sản xuất video AI Clone Avatar. Bạn duyệt và đăng — thu nhập vẫn về ví." image={img.ai}/><Section title="NetViet lo phần nặng — bạn giữ phần quyết"><Steps items={[["NHẬN BRIEF","Tiếp nhận yêu cầu."],["SẢN XUẤT AI","Tạo kịch bản và bản dựng."],["BẠN DUYỆT","Yêu cầu chỉnh sửa."],["ĐĂNG & NHẬN TIỀN","Duyệt, đăng và nhận thu nhập."]]}/></Section><Section title="Ba lớp bảo vệ hình ảnh"><Cards items={[["Đồng ý rõ ràng","Chỉ dùng trong phạm vi cho phép."],["Duyệt trước đăng","Không phát hành khi chưa duyệt."],["Theo dõi sử dụng","Lưu lịch sử và phiên bản."]]}/></Section><Cta title="Nguồn thu nhập mới với chính hình ảnh của bạn."/></Shell>}
export function PricingLanding(){return <Shell><Hero eyebrow="BẢNG GIÁ & CHÍNH SÁCH" title="Một mức phí duy nhất: 5%." sub="Không phí thành viên, không phí ẩn. Chỉ có giao dịch thành công mới có phí." image={img.price}/><Section title="Khung giá niêm yết theo 4 hạng"><div className="lp-pricing-grid">{[['Nano','200.000đ – 1.500.000đ'],['Micro','1.000.000đ – 5.000.000đ'],['Mid','4.000.000đ – 20.000.000đ'],['Macro','15.000.000đ – 80.000.000đ']].map(([n,p],i)=><article className={`lp-pricing-card ${i===1?'featured':''}`} key={n}>{i===1&&<span className="badge-popular">Phổ biến nhất</span>}<h3>{n}</h3><strong>{p}</strong><p>Mỗi bài, tuỳ ngành hàng.</p></article>)}</div></Section><Section title="Chính sách thanh toán" tint><Cards items={[["Doanh nghiệp","Nạp ví hoặc thanh toán payOS."],["KOC","Nhận 95% phí booking."],["Nền tảng","Thu 5% khi thành công."]]}/></Section><LeadForm source="landing-pricing" title="Nhận báo giá riêng"/><Cta title="Giá rõ ràng trước khi hợp tác."/></Shell>}
export function CommunityLanding(){return <Shell><Hero eyebrow="CỘNG ĐỒNG KOC 34 TỈNH THÀNH" title="Khách hàng ở tỉnh nào — KOC ở tỉnh đó." sub="Doanh nghiệp tìm đúng tiếng nói địa phương; KOC có cộng đồng và người dẫn dắt." image={img.community} primary={['Tham gia cộng đồng','/tuyen-koc']}/><Section title="Sức mạnh của KOC cùng quê"><Cards items={[["Hiểu văn hoá","Thông điệp gần gũi khách hàng."],["Chi phí hợp lý","Triển khai theo từng khu vực."],["Kết nối bền vững","Leader hỗ trợ cộng đồng."]]}/></Section><Section title="Lộ trình phủ 34 tỉnh thành" tint><Steps items={[["XÂY LEADER","Tìm người dẫn dắt."],["KẾT NỐI KOC","Mở rộng theo ngành."],["KẾT NỐI DOANH NGHIỆP","Đưa nhu cầu thật vào."],["NHÂN RỘNG","Chuẩn hoá toàn quốc."]]}/></Section><Cta title="Xây cộng đồng KOC mạnh tại quê hương bạn."/></Shell>}
export function SupportLanding(){return <Shell><section className="lp-hero"><div className="lp-hero-inner"><span className="lp-eyebrow">TRUNG TÂM HỖ TRỢ</span><h1>Chúng tôi có thể giúp gì?</h1><p className="lp-sub">Tài khoản, booking, thanh toán, affiliate và AI Clone Avatar.</p></div></section><Section title="Câu hỏi thường gặp"><Faq items={[["Đăng ký KOC thế nào?","Xác thực email, khai báo kênh, bảng giá và ký hợp đồng."],["Doanh nghiệp thanh toán thế nào?","Nạp ví hoặc payOS cho từng booking."],["Khi nào KOC được giải ngân?","Sau khi nội dung duyệt và booking hoàn thành."],["Nếu có tranh chấp?","Tạo khiếu nại trong chi tiết booking."],["Affiliate tính thế nào?","Đơn từ link riêng được đối soát theo trạng thái."]]}/></Section><LeadForm source="landing-support" title="Chưa tìm thấy câu trả lời?"/><Cta title="NetViet phản hồi trong giờ làm việc." primary={['Gửi yêu cầu','#contact-form']}/></Shell>}
